### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by Dulciphi** [HostileNetworks/ReignAdditionals#1]
I just made the recipe for the hand axe in Minetweaker. 
## Crude Hand Axe

recipes.addShapeless(reignadditionals:flintHandaxe, [minecraft:flint, minecraft:flint]);

It seems mighty powerful for a handaxe in a melee attack. I still need to check it out on more mobs, however.

**Comment by cosmicdan** [comment]
Minetweaker is good enough.
